import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";

import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { marvel } from "dh-marvel/services/marvel/marvel.service";
import { Character, GetCharacter } from "types/getCharacter";
import { CharacterTemplate } from "dh-marvel/components/CharacterTemplate";

type CharacterProps = {
  character: Character;
};

const Character: NextPage<CharacterProps> = (props) => {
  const { character } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle>
        <CharacterTemplate character={character} />
      </BodySingle>
    </>
  );
};

export default Character;

type Params = {
  id: string;
};

type CustomProps = {};

export const getServerSideProps: GetServerSideProps<CustomProps, Params> =
  async (context) => {
    const { params } = context;
    const id = params?.id;

    try {
      const { data } = await marvel.get<GetCharacter>(`/characters/${id}`);
      const character = data.data.results[0];

      return {
        props: { character },
      };
    } catch {
      return {
        props: {},
        redirect: {
          destination: "/",
          permanent: false,
        },
      };
    }
  };
