import type { NextPage } from "next";
import Head from "next/head";

import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { CheckoutTemplate } from "dh-marvel/components/CheckoutTemplate";

const Checkout: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle>
        <CheckoutTemplate />
      </BodySingle>
    </>
  );
};

export default Checkout;
