import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";

import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { Comic } from "types/getComics";
import { ComicsList } from "dh-marvel/components/ComicsList";
import { getFirstTwelveComics } from "utils/comics/getFirstTwelveComics";

type IndexProps = {
  comics: Array<Comic>;
};

const Index: NextPage<IndexProps> = (props) => {
  const { comics } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle>
        <ComicsList comics={comics} />
      </BodySingle>
    </>
  );
};

export default Index;

export const getStaticProps: GetStaticProps = async () => {
  const comics = await getFirstTwelveComics();

  return {
    props: { comics },
  };
};
